name: translations
description: A utility package to generate translations to be used in FHIR Lite.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  csv: ^5.0.1
  gsheets: ^0.4.2
